# Reference 
# https://docs.docker.com/compose/compose-file/#endpoint_mode# Reference: https://docs.docker.com/compose/compose-file/#endpoint_mode# Reference: https://docs.docker.com/compose/compose-file/#endpoint_mode
version: '3'

services:
    master:
        build:
          context: ./
          dockerfile: Dockerfile
        ports:
          - 5000:5000
        networks:
          - localNet

    node1:
        build:
          context: ./
          dockerfile: Dockerfile
        ports:
          - 5001:5000
        networks:
          - localNet
        depends_on:
          - master

    node2:
        build:
          context: ./
          dockerfile: Dockerfile
        ports:
          - 5002:5000
        networks:
          - localNet
        depends_on:
          - node1

networks:
    localNet:
