FROM ubuntu:16.04
LABEL maintainer centrifugal4@gmail.com

RUN apt-get update && apt-get install -y --no-install-recommends \
        build-essential \
        git \
        wget \
        vim \ 
        ssh \
        software-properties-common \
        python3-dev \
        python3-pip \
        python3-setuptools


WORKDIR /workspace
